Determine runtime security status
# 0 = Disabled (Not Secure)
# 1 = Hardening for unprivileged users only (Partially Secure)
# 2 = Hardening for all users (Fully Secure / Recommended)
bpf_jit_harden=2
